### ISSUE TITLE
MOLOCH error

### ISSUE THREAD

**Issue by aspel** [blacktop/docker-cuckoo#1]
When I started docker image (latest) I had an error

cat cuckoo-web-stderr---supervisor-rR8T6A.log

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/**init**.py", line 55, in **getattr**
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in **init**
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/cuckoo/web/web/settings.py", line 26, in <module>
    MOLOCH_ENABLED = cfg.moloch.get("enabled")
AttributeError: Config instance has no attribute 'moloch'

**Comment by blacktop** [comment]
thank you for letting me know I will try and address this this weekend.

**Comment by blacktop** [comment]
This is now fixed.  Thank you for bringing this to my attention.
