### ISSUE TITLE
CuckooPackageError: Unable to execute the initial process, analysis aborted.

### ISSUE THREAD

**Issue by kdeltared** [blacktop/docker-cuckoo#17]
I am trying run it in a ESXi server, and I am getting this error. Has someone gone through this?
```
2017-06-13 17:32:17,559 [cuckoo.core.resultserver] DEBUG: ResultServer running on 0.0.0.0:2042.
2017-06-13 17:32:17,560 [cuckoo.core.scheduler] INFO: Using "esx" as machine manager
2017-06-13 17:32:17,890 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2017-06-13 17:32:17,910 [cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2017-06-13 17:32:17,924 [cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2017-06-13 17:35:17,181 [cuckoo.core.scheduler] DEBUG: Processing task #15
2017-06-13 17:35:17,191 [cuckoo.core.scheduler] INFO: Starting analysis of FILE "7f4f567e55013c9bb2b13a0bb208558f1b2d46fcbd96c2132d91beb38099019b" (task #15, options "procmemdump=yes,route=none")
2017-06-13 17:35:17,219 [cuckoo.core.scheduler] INFO: Task #15: acquired machine Windows7x64_1 (label=Windows7x64_1)
2017-06-13 17:35:17,347 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 81 (interface=eth0, host=192.168.104.60, pcap=/cuckoo/storage/analyses/15/dump.pcap)
2017-06-13 17:35:17,347 [cuckoo.core.plugins] DEBUG: Started auxiliary module: Sniffer
2017-06-13 17:35:17,378 [cuckoo.common.abstracts] DEBUG: Starting machine Windows7x64_1
2017-06-13 17:35:17,378 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2017-06-13 17:35:17,401 [cuckoo.common.abstracts] DEBUG: Using snapshot Snapshot1 for virtual machine Windows7x64_1
2017-06-13 17:35:17,850 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2017-06-13 17:35:17,891 [cuckoo.core.guest] INFO: Starting analysis on guest (id=Windows7x64_1, ip=192.168.104.60)
2017-06-13 17:35:18,895 [cuckoo.core.guest] DEBUG: Windows7x64_1: not ready yet
2017-06-13 17:35:20,000 [cuckoo.core.guest] INFO: Guest is running Cuckoo Agent 0.7 (id=Windows7x64_1, ip=192.168.104.60)
2017-06-13 17:35:20,039 [cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=Windows7x64_1, ip=192.168.104.60, monitor=latest, size=3819773)
2017-06-13 17:35:20,455 [cuckoo.core.guest] DEBUG: Windows7x64_1: analysis still processing
2017-06-13 17:35:20,634 [cuckoo.core.resultserver] DEBUG: LogHandler for live analysis.log initialized.
2017-06-13 17:35:21,462 [cuckoo.core.guest] DEBUG: Windows7x64_1: analysis still processing
2017-06-13 17:35:22,355 [cuckoo.core.resultserver] DEBUG: File upload request for shots/0001.jpg
2017-06-13 17:35:22,359 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 47685
2017-06-13 17:35:22,468 [cuckoo.core.guest] DEBUG: Windows7x64_1: analysis still processing
2017-06-13 17:35:23,432 [cuckoo.core.resultserver] DEBUG: File upload request for shots/0002.jpg
2017-06-13 17:35:23,435 [cuckoo.core.resultserver] DEBUG: Uploaded file length: 56167
2017-06-13 17:35:23,472 [cuckoo.core.guest] WARNING: Windows7x64_1: analysis caught an exception
Traceback (most recent call last):
  File "C:\tmp5nvdd0\analyzer.py", line 784, in <module>
    success = analyzer.run()
  File "C:\tmp5nvdd0\analyzer.py", line 639, in run
    pids = self.package.start(self.target)
  File "C:\tmp5nvdd0\modules\packages\exe.py", line 23, in start
    return self.execute(path, args=shlex.split(args))
  File "C:\tmp5nvdd0\lib\common\abstracts.py", line 165, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

2017-06-13 17:35:23,478 [cuckoo.core.plugins] ERROR: Unable to stop auxiliary module: Sniffer
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 160, in stop
    module.stop()
  File "/usr/lib/python2.7/site-packages/cuckoo/auxiliary/sniffer.py", line 150, in stop
    "to Ubuntu-based distributions with AppArmor)?" % (out, err)
CuckooOperationalError: Error running tcpdump to sniff the network traffic during the analysis; stdout = '' and stderr = "tcpdump: eth0: You don't have permission to capture on that device\n(socket: Operation not permitted)\n". Did you enable the extra capabilities to allow running tcpdump as non-root user and disable AppArmor properly (the latter only applies to Ubuntu-based distributions with AppArmor)?
2017-06-13 17:35:23,483 [cuckoo.common.abstracts] DEBUG: Stopping machine Windows7x64_1
2017-06-13 17:35:23,483 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2017-06-13 17:35:23,650 [cuckoo.common.abstracts] DEBUG: Getting status for Windows7x64_1
2017-06-13 17:35:25,165 [cuckoo.core.scheduler] DEBUG: Released database task #15
```

**Comment by blacktop** [comment]
I am assuming your pull request fixed this issue as well?

**Comment by CrimsonGlory** [comment]
"Is it a 64-bit binary you're trying to execute on a 32-bit VM? Or an executable with a static import of a DLL not present in the VM?" (from [here](https://github.com/cuckoosandbox/cuckoo/issues/545))

**Comment by blacktop** [comment]
closing due to inactivity
