### ISSUE TITLE
Fail in analysis 

### ISSUE THREAD

**Issue by akosp94** [blacktop/docker-cuckoo#24]
Hey! I'm trying to analyze the AlienSpy trojan, downloaded the zip from TheZoo's github, put it in cuckoo and it returns with this:

cuckoo.log file
2017-11-28 12:54:35,243 [analyzer] DEBUG: Starting analyzer from: C:\tmpobb4fk
2017-11-28 12:54:35,243 [analyzer] DEBUG: Pipe server name: \??\PIPE\JBDFKqDzzpSDzIvZtTPa
2017-11-28 12:54:35,243 [analyzer] DEBUG: Log pipe server name: \??\PIPE\VuJXYpwKYFspWUaJkPpclTJKt
2017-11-28 12:54:35,368 [analyzer] DEBUG: Started auxiliary module DbgView
2017-11-28 12:54:35,789 [analyzer] DEBUG: Started auxiliary module Disguise
2017-11-28 12:54:36,368 [modules.auxiliary.dumptls] WARNING: You're not running the Cuckoo Agent as Administrator. Doing so will improve your analysis results!
2017-11-28 12:54:36,414 [analyzer] DEBUG: Started auxiliary module DumpTLSMasterSecrets
2017-11-28 12:54:36,507 [analyzer] DEBUG: Started auxiliary module Human
2017-11-28 12:54:36,789 [modules.auxiliary.installcert] INFO: Successfully installed PFX certificate.
2017-11-28 12:54:36,789 [analyzer] DEBUG: Started auxiliary module InstallCertificate
2017-11-28 12:54:36,789 [analyzer] DEBUG: Started auxiliary module Reboot
2017-11-28 12:54:36,882 [analyzer] DEBUG: Started auxiliary module RecentFiles
2017-11-28 12:54:36,976 [analyzer] DEBUG: Started auxiliary module Screenshots
2017-11-28 12:54:36,976 [analyzer] DEBUG: Started auxiliary module LoadZer0m0n
2017-11-28 12:54:39,523 [lib.api.process] ERROR: Failed to execute process from path 'C:\\Program Files\\Java\\jre1.8.0_151\\bin\\java.exe' with arguments ['bin\\inject-x64.exe', '--resume-thread', '--pid', '2796', '--tid', '1476', '--apc', '--dll', 'C:\\tmpobb4fk\\bin\\monitor-x64.dll', '--config', 'c:\\users\\szakdoga\\appdata\\local\\temp\\tmpw0nkbx'] (Error: Command '['bin\\inject-x64.exe', '--resume-thread', '--pid', '2796', '--tid', '1476', '--apc', '--dll', 'C:\\tmpobb4fk\\bin\\monitor-x64.dll', '--config', 'c:\\users\\szakdoga\\appdata\\local\\temp\\tmpw0nkbx']' returned non-zero exit status 1)

first of all, how to run cuckoo agent as admin? I started the vm and checked but did not found such option.

Also there's an exception which is listed in the analysis.log

2017-11-28 12:54:44,791 [cuckoo.core.guest] WARNING: cuckoo1: analysis caught an exception
Traceback (most recent call last):
  File "C:/tmpobb4fk/analyzer.py", line 794, in <module>
    success = analyzer.run()
  File "C:/tmpobb4fk/analyzer.py", line 649, in run
    pids = self.package.start(self.target)
  File "C:\tmpobb4fk\modules\packages\jar.py", line 23, in start
    return self.execute(java, args=args, trigger="file:%s" % path)
  File "C:\tmpobb4fk\lib\common\abstracts.py", line 165, in execute
    "Unable to execute the initial process, analysis aborted."
CuckooPackageError: Unable to execute the initial process, analysis aborted.

what the heck am I doing wrong?

**Comment by hop-dev** [comment]
To run the agent as admin you need to open cmd as administrator by right clicking the icon then > run as administrator.

**Comment by blacktop** [comment]
@akosp94 did @hoppers2k9 comment help you?  If so can we close this issue?

**Comment by akosp94** [comment]
Issue solved thank you
