### ISSUE TITLE
api and cuckoo exited after docker-compose, web runs normally but all files show pending 

### ISSUE THREAD

**Issue by dagrons** [blacktop/docker-cuckoo#45]
The docker_cuckoo_api and docker_cuckoo_cuckoo exited after i execute "docker-compose up -d".
the output for "docker logs docker_cuckoo_api":
> sudo docker logs docker-cuckoo_api_1

> ===> Use default ports and hosts if not specified...
> ES_HOST=elasticsearch
> ES_PORT=9200
> MONGO_HOST=mongo
> MONGO_TCP_PORT=27017
> POSTGRES_HOST=postgres
> POSTGRES_TCP_PORT=5432
> RESULTSERVER_HOST=0.0.0.0
> RESULTSERVER_PORT=2042
> 
> ===> Update /cuckoo/conf/reporting.conf if needed...
> 
> ===> Waiting on elasticsearch(http://elasticsearch:9200) to start........
> Elasticsearch is ready!
> 
> ===> Waiting for MongoDB(mongo:27017) to start...MongoDB is ready!
> 
> ===> Waiting for Postgres(postgres:5432) to start...Postgres is ready!
> Traceback (most recent call last):
>   File "/usr/bin/cuckoo", line 11, in <module>
>     load_entry_point('Cuckoo==2.0.5.3', 'console_scripts', 'cuckoo')()
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/cuckoo/main.py", line 463, in api
>     Database().connect()
>   File "/usr/lib/python2.7/site-packages/cuckoo/core/database.py", line 444, in connect
>     self._create_tables()
>   File "/usr/lib/python2.7/site-packages/cuckoo/core/database.py", line 452, in _create_tables
>     "Unable to create or connect to database: %s" % e
> cuckoo.common.exceptions.CuckooDatabaseError: Unable to create or connect to database: (psycopg2.IntegrityError) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
> DETAIL:  Key (typname, typnamespace)=(status_type, 2200) already exists.
>  [SQL: "CREATE TYPE status_type AS ENUM ('pending', 'running', 'completed', 'reported', 'recovered', 'failed_analysis', 'failed_processing', 'failed_reporting')"]

**Comment by vaibhavpandey86** [comment]
hello @dagrons you got any solution for this issue... i am facing almost the same issue.

===> Waiting on elasticsearch(http://elasticsearch:9200) to start................................................................
===> Use default ports and hosts if not specified...
ES_HOST=elasticsearch
ES_PORT=9200
MONGO_HOST=mongo
MONGO_TCP_PORT=27017
POSTGRES_HOST=postgres
POSTGRES_TCP_PORT=5432
RESULTSERVER_HOST=0.0.0.0
RESULTSERVER_PORT=2042

===> Update /cuckoo/conf/reporting.conf if needed...

===> Waiting on elasticsearch(http://elasticsearch:9200) to start................................................................
Elasticsearch is not running or is not healthy.
Address: http://elasticsearch:9200

**Comment by dagrons** [comment]
No, I give up...😂

**Comment by dagrons** [comment]
@vaibhavpandey86 No, I give up...😂
